modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Bigger%20Sponge%20Absorption%20Radius"
logoFile="icon.png"

[[mods]]
modId="biggerspongeabsorptionradius"
version="3.4"
displayName="Bigger Sponge Absorption Radius"
displayURL="https://serilum.com/mod/bigger-sponge-absorption-radius"
authors="Rick South"
description='''Each extra sponge block placed next to another increases the water absorption radius.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.biggerspongeabsorptionradius]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biggerspongeabsorptionradius]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "biggerspongeabsorptionradius_neoforge.mixins.json"