modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Bigger%20Sponge%20Absorption%20Radius"
logoFile="icon.png"

[[mods]]
modId="biggerspongeabsorptionradius"
version="3.7"
displayName="Bigger Sponge Absorption Radius"
displayURL="https://serilum.com/mod/bigger-sponge-absorption-radius"
authors="Rick South"
description='''Each extra sponge block placed next to another increases the water absorption radius.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.biggerspongeabsorptionradius]]
    modId="collective"
    type="required"
    versionRange="[7.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biggerspongeabsorptionradius]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "biggerspongeabsorptionradius.mixins.json"